#Install Chocolatey (https://chocolatey.org/)
Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco feature enable -n allowGlobalConfirmation

#Install Chocolatey packages
choco install 1password
choco install 7zip
choco install brave
choco install bulkrenameutility
choco install ccleaner
choco install ConEmu
choco install DotNet3.5
choco install DotNet4.5
choco install DotNet4.5.2
choco install DotNet4.6
choco install DotNet4.6
choco install DotNet4.6.2
choco install dotnetcore
choco install dropbox
choco install Firefox
choco install foxitreader
choco install git
choco install grepwin
choco install linqpad5
choco install nuget.commandline
choco install nunit-console-runner
choco install OpenOffice
choco install poshgit
choco install ReSharper
choco install Slack
choco install Spotify
choco install sql-server-management-studio
choco install steam
choco install sublimetext3
choco install utorrent
choco install VisualStudio2017Enterprise
choco install VisualStudioCode
choco install vlc
choco install vscode-cake
choco install vscode-csharp
choco install vscode-csharpextensions
choco install vscode-gitignore
choco install vscode-gitattributes
choco install vscode-mssql
choco install vscode-powershell
